#!/bin/sh

export JAVA_OPTS=""
export PROJECT_DIR="$(dirname $0)/.."

main_class=trilby.main.Main
verbose_gc=false
gc_details=true
need_gc=true
use_jline=true

while true; do case "$1" in
    --genheap)
        main_class=trilby.main.GenHeap
        shift
        ;;
    --hprof)
        JAVA_OPTS+=" -agentlib:hprof=cpu=samples,depth=35,interval=10"
        shift
        ;;
    --g1)
        JAVA_OPTS+=" -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC"
        gc_details=false
        need_gc=false
        shift
        ;;
    --gc)
        verbose_gc=true
        shift
        ;;
    --nojline)
        use_jline=false
        shift
        ;;
    --*)
        break
        ;;
    -*)
        JAVA_OPTS+=" $1"
        shift
        ;;
    *)
        break
        ;;
esac; done

if $verbose_gc; then
    JAVA_OPTS+=" -verbose:gc"
    if $gc_details; then
        JAVA_OPTS+=" -XX:+PrintGCDetails"
    fi
fi

if $need_gc; then
    JAVA_OPTS+=" -XX:+UseConcMarkSweepGC"
fi

# 'sbt start-script' exports a broken shell command under OS/X so override
# its setting of PROJECT_DIR

sed -i -e '/^PROJECT_DIR=/s/^/#/' $PROJECT_DIR/target/start
exec $PROJECT_DIR/target/start trilby.main.Main "$@"


