#!/bin/sh

export PROJECT_DIR=$(dirname $0)/..

if [ ! -e $PROJECT_DIR/target/start ]; then
    echo "$PROJECT_DIR/target/start" is missing >&2
    echo "You probably forgot to run 'sbt start-script'" >&2
    exit 1
fi

# 'sbt start-script' exports a broken shell command under OS/X so override
# its setting of PROJECT_DIR

sed -i -e '/^PROJECT_DIR=/s/^/#/' $PROJECT_DIR/target/start

export JAVA_OPTS=""

verbose_gc=false
gc_details=true
need_gc=true
run_what=trilby
use_jline=--jline

while true; do case "$1" in
    --dumpoome)
        JAVA_OPTS+=" -XX:+HeapDumpOnOutOfMemoryError"
        shift
        ;;
    --genheap)
        run_what=gen_heap
        shift
        ;;
    --hprof)
        JAVA_OPTS+=" -agentlib:hprof=cpu=samples,depth=35,interval=5"
        shift
        ;;
    --g1)
        JAVA_OPTS+=" -XX:+UseG1GC"
        gc_details=false
        need_gc=false
        shift
        ;;
    --gc|--verbosegc)
        verbose_gc=true
        shift
        ;;
    --nojline)
        use_jline=
        shift
        ;;
    --offline)
        run_what=offline_tests
        shift
        ;;
    --*)
        break
        ;;
    -*)
        JAVA_OPTS+=" $1"
        shift
        ;;
    *)
        break
        ;;
esac; done

# Primary run target is trilby itself
#

run_trilby() {
    exec $PROJECT_DIR/target/start trilby.main.Main $use_jline "$@"
}

# Run tests against offline / non-public heaps
#

run_offline_tests() {
    $HOME/work/trilby-ls/testit "$@"
}

# Generate test heaps
#

run_gen_heap() {
    gen_heap smallheap.hprof 10000
}

gen_heap() {
    local filename="$1"
    local numObjects="$2"
    echo "Generating $filename with $numObjects test objects"
    rm -f $filename
    $PROJECT_DIR/target/start trilby.util.GenHeap $numObjects &
    sleep 2
    pid=$(jps -l | awk '$2 == "trilby.util.GenHeap" { print $1; }')
    jmap -dump:format=b,file=$filename $pid
    echo "Killing GenHeap & waiting"
    kill $pid
    wait $pid
    echo "Done with $filename"
}

if $verbose_gc; then
    JAVA_OPTS+=" -verbose:gc"
    if $gc_details; then
        JAVA_OPTS+=" -XX:+PrintGCDetails"
    fi
fi

if $need_gc; then
    JAVA_OPTS+=" -XX:+UseConcMarkSweepGC"
fi

run_$run_what "$@"

